#pragma once

#include"Node.h"
#include"Expr.h"
#include"Stmt.h"

#include"Value.h"

#include"ArrayExpr.h"
#include"AssignmentExpr.h"
#include"BinaryExpr.h"
#include"BlockStmt.h"
#include"BoolLiteral.h"
#include"CallExpr.h"
#include"Decl.h"
#include"DoWhileStmt.h"
#include"ForStmt.h"
#include"FunctionDecl.h"
#include"FunctionExpr.h"
#include"Identifier.h"
#include"IfStmt.h"
#include"Literal.h"
#include"LogicExpr.h"
#include"NewExpr.h"
#include"NumberLiteral.h"
#include"Program.h"
#include"ReturnStmt.h"
#include"SequenceExpr.h"
#include"StringConstant.h"
#include"Tag.h"
#include"UnaryExpr.h"
#include"UpdateExpr.h"
#include"VariableDeclaration.h"
#include"VariableDeclarator.h"
#include"WhileStmt.h"
