#pragma once
//保留字枚举常量及标签
enum Tag {
	//保留关键字
	ABSTRACT=256, ARGUMENTS, BOOLEAN,BREAK,BYTE,
	CASE,CATCH,CHAR,CLASS,CONST,
	CONTINUE,DEBUGGER,DEFAULT,DELETE,DO,
	DOUBLE,ELSE,ENUM,EVAL,EXPORT,
	EXTENDS,FALSE,FINAL,FINALLY,FLOAT,
	FOR,FUNCTION,GOTO,IF,IMPLEMENTS,
	IMPORT,IN,INSTANCEOF,INT,INTERFACE,
	LET,LONG,NATIVE,NEW,Null,
	PACKAGE,PRIVATE,PROTECTED,PUBLIC,RETURN,
	SHORT,STATIC,SUPER,SWITCH,SYNCHRONIZED,
	THIS,THROW,THROWS,TRANSIENT,TRUE,
	TRY,TYPEOF,VAR,VOID,VOLATILE,
	WHILE,WITH,YIELD,
	ARRAY,DATE,HASOWNPROPERTY,
	Infinity,ISFINITE,ISNAN,ISPROTOTYPEOF,
	LENGTH,MATH,Nan,NAME,NUMBER,OBJECT,
	PROTOTYPE,STRING,TOSTRING,UNDEFINED,VALUEOF,
	//标签
	AND,OR,EQ,NE,LE,GE,ID,
	ADD,//连加
	MINUS, //连减
	LAST//最后的标识
};